<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>
</head>
<body>
<div style="text-align: center;">&nbsp; &nbsp;<span style="color:#000000"><strong><span style="font-size:18px"><span style="font-family:georgia,times,times new roman,serif">Bot Characteristics</span></span></strong></span></div>

<ul>
	<li style="text-align: left;"><span style="color:rgb(0, 0, 0); font-family:georgia,times,times new roman,serif; font-size:14px; line-height:1.6em">Bot operating from a server hosted in Data Center</span></li>
	<li style="text-align: left;"><span style="color:rgb(0, 0, 0); font-family:georgia,times,times new roman,serif; font-size:14px; line-height:1.6em">Browser capability not found</span></li>
	<li style="text-align: left;"><span style="color:rgb(0, 0, 0); font-family:georgia,times,times new roman,serif; font-size:14px; line-height:1.6em"><span style="color:rgb(0, 0, 0); font-family:georgia,times,times new roman,serif; font-size:14px; line-height:1.6em"><span style="font-size:14px"><span style="font-family:georgia,times,times new roman,serif"><span style="text-align:center" valign="top"><span style="color:rgb(0, 0, 0)">Web</span></span></span></span></span></span><span style="color:#000000"><span style="font-family:georgia,times,times new roman,serif; font-size:14px; line-height:1.6em"><span style="font-family:georgia,times,times new roman,serif; font-size:14px; line-height:1.6em"><span style="font-size:14px"><span style="font-family:georgia,times,times new roman,serif"><span style="text-align:center" valign="top"> session and c<span style="color:#000000"><span style="font-family:georgia,times,times new roman,serif; font-size:14px; line-height:1.6em"><span style="font-family:georgia,times,times new roman,serif; font-size:14px; line-height:1.6em"><span style="font-size:14px"><span style="font-family:georgia,times,times new roman,serif"><span style="text-align:center" valign="top"><span style="color:#000000"><span style="font-family:georgia,times,times new roman,serif; font-size:14px; line-height:1.6em"><span style="font-family:georgia,times,times new roman,serif; font-size:14px; line-height:1.6em"><span style="font-size:14px"><span style="font-family:georgia,times,times new roman,serif"><span style="text-align:center" valign="top"><span style="font-size:14px"><span style="font-family:georgia,times,times new roman,serif">ookies are being tampered</span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></li>
	<li style="text-align: left;"><span style="color:#000000"><span style="font-family:georgia,times,times new roman,serif; font-size:14px; line-height:1.6em"><span style="font-family:georgia,times,times new roman,serif; font-size:14px; line-height:1.6em"><span style="font-size:14px"><span style="font-family:georgia,times,times new roman,serif"><span style="text-align:center" valign="top"><span style="color:#000000"><span style="font-family:georgia,times,times new roman,serif; font-size:14px; line-height:1.6em"><span style="font-family:georgia,times,times new roman,serif; font-size:14px; line-height:1.6em"><span style="font-size:14px"><span style="font-family:georgia,times,times new roman,serif"><span style="text-align:center" valign="top"><span style="font-size:14px"><span style="font-family:georgia,times,times new roman,serif"><span style="font-size:14px"><span style="font-family:georgia,times,times new roman,serif"><span style="color:#000000">Programmatic access of URLs identified</span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></li>
	<li style="text-align: left;"><span style="color:#000000"><span style="font-family:georgia,times,times new roman,serif; font-size:14px; line-height:1.6em"><span style="font-family:georgia,times,times new roman,serif; font-size:14px; line-height:1.6em"><span style="font-size:14px"><span style="font-family:georgia,times,times new roman,serif"><span style="text-align:center" valign="top"><span style="color:#000000"><span style="font-family:georgia,times,times new roman,serif; font-size:14px; line-height:1.6em"><span style="font-family:georgia,times,times new roman,serif; font-size:14px; line-height:1.6em"><span style="font-size:14px"><span style="font-family:georgia,times,times new roman,serif"><span style="text-align:center" valign="top"><span style="font-size:14px"><span style="font-family:georgia,times,times new roman,serif"><span style="font-size:14px"><span style="font-family:georgia,times,times new roman,serif"><span style="color:#000000">Referrer URL is tampered</span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></li>
	<li style="text-align: left;"><span style="color:#000000"><span style="font-family:georgia,times,times new roman,serif; font-size:14px; line-height:1.6em"><span style="font-family:georgia,times,times new roman,serif; font-size:14px; line-height:1.6em"><span style="font-size:14px"><span style="font-family:georgia,times,times new roman,serif"><span style="text-align:center" valign="top"><span style="font-size:14px"><span style="font-family:georgia,times,times new roman,serif"><span style="font-family:georgia,times,times new roman,serif; font-size:14px; line-height:1.6em"><span style="font-size:14px"><span style="font-family:georgia,times,times new roman,serif"><span style="text-align:center" valign="top"><span style="font-family:georgia,times,times new roman,serif; font-size:14px; line-height:1.6em"><span style="font-size:14px"><span style="font-family:georgia,times,times new roman,serif"><span style="text-align:center" valign="top"><span style="font-size:14px"><span style="font-family:georgia,times,times new roman,serif"><span style="text-align:center" valign="top"><span style="font-family:georgia,times,times new roman,serif; font-size:14px; line-height:1.6em"><span style="font-size:14px"><span style="font-family:georgia,times,times new roman,serif"><span style="text-align:center" valign="top"><span style="font-family:georgia,times,times new roman,serif; font-size:14px; line-height:1.6em"><span style="font-size:14px"><span style="font-family:georgia,times,times new roman,serif"><span style="text-align:center" valign="top"><span style="font-size:14px"><span style="font-family:georgia,times,times new roman,serif"><span style="text-align:center" valign="top"><span style="font-size:14px"><span style="font-family:georgia,times,times new roman,serif">Programmatic browser behaviour</span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></li>
</ul>


</body>
</html>